### ISSUE TITLE
Maps and Graphs in the GUI branch

### ISSUE THREAD

**Issue by SlothfulAlfred** [SlothfulAlfred/Air-Pollution-App-CS#19]
### maps
Even if the map won't be interactive, you should at the very least:

- make a function to create them as needed, don't just upload the pictures
- change the zoom **please**; if the map is of the USA, I don't need to see Mexico and Canada too
- I don't know if it's a mistake or a WIP, but if it's a mistake remove that color bar on the side (if it's a WIP then change the values because right now they're all pretty much the same exact color)

### graphs
I have no idea why you made graphs since it's my responsibility anyway but... I guess I'll provide feedback for those too?

- The graphs aren't organized from least to greatest or vice-versa which makes it a little hard to read
- The graph for the USA is not complete, there are 51 states you included about 10-15
- I already made a function that creates the bar graphs so you can feel free to delete the images you uploaded and provide feedback on the function that I uploaded

Also, **finish the code review!!!!** The pull requests have been left totally untouched for the last few days, it's really not a lot of work.

**Comment by Rishbob** [comment]
All issues in regards to the maps should be dealt with now.
