### ISSUE TITLE
Preparing to merge the GUI branch.

### ISSUE THREAD

**Issue by SlothfulAlfred** [SlothfulAlfred/Air-Pollution-App-CS#20]
Before we merge the GUI branch we need to fix a few things so that our entire project doesn't get messed up.

- [x] Make the GUI folder structure the same as the main branch (excluding newly added folders i.e images)
- [ ] Make sure that the files already in the main branch haven't been edited (i.e country.py, region.py)

It would have been better to merge the branches more frequently but it's not really a big deal, we just need to do the above.

**Comment by Rishbob** [comment]
If you're merging, do you know if usa.txt in the main branch has latitude/longitude data for District of Columbia? I added it to the GUI branches version.

**Comment by SlothfulAlfred** [comment]
Yeah, I noticed that it didn't have them and I updated it on my local version of the app. Maybe I forgot to commit the changes on GitHub, you can add that directly to the main branch too, thank you Rishabh.
