### ISSUE TITLE
Module Import Issues

### ISSUE THREAD

**Issue by Rishbob** [SlothfulAlfred/Air-Pollution-App-CS#22]
I'm trying to import functions and classes from source/helpers into gui.py, which is currently in source/gui. However, the program continously throws the following error:

ModuleNotFoundError: No module named 'source'

As far as I can tell, Python relative path imports require the imported file to be either in the same directory or a lower directory than the file they are being imported to. As of now, the only way I can thus see to remedy the issue is to move gui.py into source/helpers, and reformat it into a function that is called by main.py. Is there any other possible solution, or is that change necessary?

**Comment by SlothfulAlfred** [comment]
I can't do anything unless you send the code and the error message. However, you can import files from anywhere within the current working directory or any directories within the path. It's quite contradictory to be importing `tkinter` and then say that it's impossible to import from outside the CWD.

**Comment by Rishbob** [comment]
Understood, here's the full code (the specific program you're looking for is source/gui/gui.py):

[Air-Pollution-App-CS-GUI.zip](https://github.com/SlothfulAlfred/Air-Pollution-App-CS/files/5789967/Air-Pollution-App-CS-GUI.zip)


And the error message is as follows:

C:\Users\Asus\Downloads\venv\Scripts\python.exe C:/Users/Asus/Downloads/Air-Pollution-App-CS-GUI/source/helpers/gui.py
Traceback (most recent call last):
  File "C:\Users\Asus\Downloads\Air-Pollution-App-CS-GUI\source\helpers\gui.py", line 12, in <module>
    from source.helpers.country import Country
ModuleNotFoundError: No module named 'source'

Process finished with exit code 1



NOTE: If the zip doesn't upload correctly let me know, I'll email it to you instead.

**Comment by SlothfulAlfred** [comment]
In the future, just copy and paste the code so I don't have to search around inside the file. Regardless, if you want to go up to the current folder then you can put `.whatever_you_want_to_import_from_the_same_folder` and if you want to go two levels up than put `..different_folder.different_file`. In your situation the two dots would take you up to the `source` folder and from there you can add the rest of the path.

**Comment by Rishbob** [comment]
I attempted the fix you mentioned, and got the following error:
![Screenshot (6)](https://user-images.githubusercontent.com/43894878/104096216-1c9c9680-5269-11eb-961c-ba809dbd0590.png)
For now, I'm going to move gui.py into source/helpers, and make it into a function that is called by main.py.

**Comment by SlothfulAlfred** [comment]
![testing_imports](https://user-images.githubusercontent.com/75184429/104104236-dcdbac00-5274-11eb-8903-ba8fd4c2a624.PNG)

I have no idea why your imports aren't working, Check through your files to see if you messed with the directory somewhere; you might have forgotten to delete some of your earlier code that changed the directory. As you can see from:
```
Classes
    |import_test
        |import_testing
            |module1.py
```

I'm importing:
```
Classes
    |testing_testing
        |country.py
```
without raising any issues.

**Comment by Rishbob** [comment]
On my end, it seems that changing the Pycharm working directory doesn't actually do anything. So at least on my end, I'll need to reintergrate the path change code to make it work again.
